### PR TITLE
scale penalty with samples

### PR DESCRIPTION
**Pull request by jbrea**
This is a first attempt at #108.

There are quite a few docstrings that still need to be adjusted.
@tlienart can you have a look at the `RidgeRegression` docstring for an example how I intended to adjust them?

### CODE REVIEW

**Comment by tlienart** [comment]
Apologies for the late reply, with family duties around the holidays I didn't have much time to look into this.

This looks great, thank you very much. One small note is that we could add a function `get_penalty_scale(glr, n)` which would return `glr.penalty * ifelse(glr.scale_penalty_with_samples, float(n), 1.0)`, that might be a bit less clunky in the code but it's essentially aesthetics. I can do that later.

I'm otherwise happy with this as it is, thanks!

**Comment by jbrea** [comment]
Thanks for the feedback! I use a `get_penalty_scale` function now and fixed the docstrings.

By the way, when I started working on this PR I considered for a moment an alternative implementation with a wrapper
```julia
struct AverageLoss{L} <: Loss
    loss::L
end

(al::AverageLoss)(x::AVR, y::AVR) = al.loss(x, y)/length(y)
```
I found this pretty neat, but it would have required some major refactoring, mostly because of the parametric dispatch on `glr` for `_solver`, `_fit` etc. Are all these type restrictions really needed? Or could one get rid of them, maybe with a few traits?

But I am also fine with the current implementation. Please feel free to merge whenever you feel this PR is ready.

**Comment by tlienart** [comment]
I think the CI failure with Julia1 is due to MLJBase changes. The easiest is probably to just put the minimum Julia version for MLJLinearModels 0.6 to 1.5.

**Comment by tlienart** [comment]
Thanks **a lot** @jbrea for this!

With respect to `AverageLoss`, this sounds great and happy to help you with the refactoring if you need any help there.

**Pull request merged**
